"""empty message

Revision ID: a81136adf42b
Revises: 4ccc5ebeca8d
Create Date: 2020-12-14 16:31:03.773466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81136adf42b'
down_revision = '4ccc5ebeca8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation_scheme', sa.Column('tag', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculation_scheme', 'tag')
    # ### end Alembic commands ###
